version: "3.8"
services:
  moto-postgres:
    image: postgres:15.3-alpine
    container_name: moto-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      
  moto-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: moto-pgadmin
    restart: always
    depends_on:
      - moto-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8082:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
      
  moto-seq:
    image: datalust/seq:latest
    container_name: moto-seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8032:80

  moto-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'moto-rabbitmq'
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  application:
    build:
      context: .
    container_name: moto
    restart: always
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_ENVIRONMENT: Development
    depends_on:
      - moto-postgres
      - moto-seq
      - moto-rabbitmq
