using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Moto.Domain.Base;

namespace Moto.Persistence.Extensions;

/// <summary>
/// This static class provides extension methods for configuring entities that inherit from <see cref="BaseEntity"/>.
/// It is designed to centralize the configuration of common properties for all entities in the application,
/// ensuring consistency across the database schema for base properties like Id and DomainEvents.
/// </summary>
internal static class EntityTypeBuilderExtensions
{
    internal static void ConfigureBaseEntity<TEntity>(this EntityTypeBuilder<TEntity> builder)
        where TEntity : BaseEntity
    {
        // Sets the primary key for the entity to the Id property.
        builder
            .HasKey(entity => entity.Id);

        // Configures the Id property to be required (NOT NULL) and not generated by the database.
        builder
            .Property(entity => entity.Id)
            .IsRequired()
            .UseIdentityAlwaysColumn();

        // Ignores the DomainEvents property for the entity.
        builder
            .Ignore(entity => entity.DomainEvents);
    }
}