using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Moto.Domain.Base;

namespace Moto.Persistence.Extensions;

internal static class EntityTypeBuilderExtensions
{
    internal static void ConfigureBaseEntity<TEntity>(this EntityTypeBuilder<TEntity> builder)
        where TEntity : BaseEntity
    {
        // Sets the primary key for the entity to the Id property.
        builder
            .HasKey(entity => entity.Id);

        // Configures the Id property to be required (NOT NULL) and not generated by the database.
        builder
            .Property(entity => entity.Id)
            .IsRequired()
            .UseIdentityAlwaysColumn();

        // Ignores the DomainEvents property for the entity.
        builder
            .Ignore(entity => entity.DomainEvents);
    }
}